### PR TITLE
Added Example and tested funtionalities

### PR DESCRIPTION
**Pull request by decarlof**
Added epics interface and tested on PVs from the APS. Added examples to test file integrity (structure and array dimensions), directory monitoring and data quality functions. All is working great!
In the process I propose new names for modules and functions. The docs are updated.

### CODE REVIEW

**Comment by decarlof** [comment]
Good point about the PVs.  Also you might find it easier to read the changes I propose in the doc so I made  a build under my account at http://dquality.readthedocs.org/en/latest/
Let's keep the pull request open till we meet on Friday if you don't mind, same changes I made are really just a proposal.

**Comment by decarlof** [comment]
ops! you just merged ... well is github =  we can always undo it ....

**Comment by bfrosik** [comment]
ups, didn't read your emal.
I will undo it and keep it open as you suggested.

**Comment by dgursoy** [comment]
will go through soon... I would keep the project name dquality for both the Github and Docs (to have the same name with the `import quality`).

**Pull request merged**
