### PR TITLE
Config file

### PR DESCRIPTION
**Pull request by decarlof**
Config files are now provided as downloadable templates part of the docs.
Config file location is moved to home directory.
Updated docs and tested all functions.

### CODE REVIEW

**Comment by decarlof** [comment]
You can check the new config file layout at:

http://dquality.readthedocs.org/en/latest/source/install.html#id3

all config files are available from the docs as downloadable files:
http://dquality.readthedocs.org/en/latest/source/api/dquality.pv.html

**Comment by decarlof** [comment]
I solved the conflicts with Doga's fork and merged.

**Comment by bfrosik** [comment]
Thank you Francesco, I will take a look and commit.
Barbara

**Comment by decarlof** [comment]
This pull request incorporates all Doga's changes now.

**Pull request merged**
