### PR TITLE
added pvVerifier

### PR DESCRIPTION
**Pull request by bfrosik**

### CODE REVIEW

**Comment by bfrosik** [comment]
I will change it to this. There are a few more: qualityChecks -> qualitychecks, structureVerifier -> structureverifier, but how about basicHD5.json. I would leave it as is, since this is json file.

**Comment by dgursoy** [comment]
Just for the python modules. JSON can stay as is.

Does it make sense to have a module called verifier and put pvVerifier and structureVerifier in it?

**Comment by bfrosik** [comment]
That's a good point. The pvverifier verifies process variables, the structureverifier verifies the structure of a file (i.e. tags, dimentions, etc.), and the verifier is the real time application that calls the verifiers plus quality checks. I would leave the two (pvverifier and structureverifier) as is but rename verifier. How about dataintegrityvalidator? Please share your idea to remane the file, if this is too long.

**Comment by dgursoy** [comment]
Why rename verifier? I would keep `verifier` as is, since it's simpler.

**Comment by bfrosik** [comment]
then let's keep it.

**Pull request merged**
