### PR TITLE
Accomodate for multiple instruments at the same beamline

### PR DESCRIPTION
**Pull request by decarlof**
Please review but don't accept yet, I still need to update the docs.
Also there is a conflict since we both modified the wrapper functions, we can fix that manually.

### CODE REVIEW

**Comment by bfrosik** [comment]
Francesco, this look really good. I like the new dquality/check directory with the code for all cases.
And then the demo that include 32id specifics. The 'wrapper' is not needed, since it is all in demo - looks nice and clean.

**Comment by decarlof** [comment]
I was also thinking to remove from the functions in check.py the parser since this is now also running in the corresponding demo function (= the parameter are already checked in the demo function so there is no need to repeat the parsing again) unless you expect someone to directly call them from main.

**Comment by bfrosik** [comment]
Yes, I agree. I thought about the same, while writing the wrappers, but thought that both will be used. With the refactoring it seems redundant.

**Comment by decarlof** [comment]
@bfrosik ok docs now builds again,
 I removed the redundant parsers and added a 'default' instrument folder that will be used if a station has only one instrument and/or does not pass the 'instrument' parameter in the function call; still I need to figure out how to make the parser work if a parameter is missing ...

**Comment by decarlof** [comment]
@bfrosik compiles and runs without errors but logs complains does not find files:

2016-06-14T19:32:08-0500:  ERROR:  dquality.pv:  configuration error: pv_file is not configured
2016-06-14T19:32:13-0500:  ERROR:  dquality.pv:  configuration error: pvs is not configured

etc. 

I think I need a better understanding of what the `get_file` function in [utilities](https://github.com/bfrosik/data-quality/blob/master/dquality/common/utilities.py) does with the statement `file = conf[config_name]`.

**Comment by decarlof** [comment]
@bfrosik thank you for the dictionary tips. All works now, please have  a look. Let me know when you plan to merge, I have  a quick solution for the merge conflict.

**Comment by bfrosik** [comment]
great, I will merge

**Comment by bfrosik** [comment]
You did a great work Francesco with reorganizing. What would be the merge tip?

**Pull request merged**
